/*
Airflow API (Stable)

Testing DAGAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package airflow

import (
	openapiclient "github.com/drfaust92/airflow-client-go/airflow"
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_airflow_DAGAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DAGAPIService DeleteDag", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dagId string

		httpRes, err := apiClient.DAGAPI.DeleteDag(context.Background(), dagId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DAGAPIService GetDag", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dagId string

		resp, httpRes, err := apiClient.DAGAPI.GetDag(context.Background(), dagId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DAGAPIService GetDagDetails", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dagId string

		resp, httpRes, err := apiClient.DAGAPI.GetDagDetails(context.Background(), dagId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DAGAPIService GetDagSource", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var fileToken string

		resp, httpRes, err := apiClient.DAGAPI.GetDagSource(context.Background(), fileToken).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DAGAPIService GetDags", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.DAGAPI.GetDags(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DAGAPIService GetTask", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dagId string
		var taskId string

		resp, httpRes, err := apiClient.DAGAPI.GetTask(context.Background(), dagId, taskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DAGAPIService GetTasks", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dagId string

		resp, httpRes, err := apiClient.DAGAPI.GetTasks(context.Background(), dagId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DAGAPIService PatchDag", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dagId string

		resp, httpRes, err := apiClient.DAGAPI.PatchDag(context.Background(), dagId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DAGAPIService PatchDags", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.DAGAPI.PatchDags(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DAGAPIService PostClearTaskInstances", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dagId string

		resp, httpRes, err := apiClient.DAGAPI.PostClearTaskInstances(context.Background(), dagId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DAGAPIService PostSetTaskInstancesState", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dagId string

		resp, httpRes, err := apiClient.DAGAPI.PostSetTaskInstancesState(context.Background(), dagId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DAGAPIService ReparseDagFile", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var fileToken string

		httpRes, err := apiClient.DAGAPI.ReparseDagFile(context.Background(), fileToken).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
