/*
Airflow API (Stable)

Testing TaskInstanceAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package airflow

import (
	openapiclient "./airflow"
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_airflow_TaskInstanceAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TaskInstanceAPIService GetExtraLinks", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dagId string
		var dagRunId string
		var taskId string

		resp, httpRes, err := apiClient.TaskInstanceAPI.GetExtraLinks(context.Background(), dagId, dagRunId, taskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskInstanceAPIService GetLog", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dagId string
		var dagRunId string
		var taskId string
		var taskTryNumber int32

		resp, httpRes, err := apiClient.TaskInstanceAPI.GetLog(context.Background(), dagId, dagRunId, taskId, taskTryNumber).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskInstanceAPIService GetMappedTaskInstance", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dagId string
		var dagRunId string
		var taskId string
		var mapIndex int32

		resp, httpRes, err := apiClient.TaskInstanceAPI.GetMappedTaskInstance(context.Background(), dagId, dagRunId, taskId, mapIndex).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskInstanceAPIService GetMappedTaskInstanceDependencies", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dagId string
		var dagRunId string
		var taskId string
		var mapIndex int32

		resp, httpRes, err := apiClient.TaskInstanceAPI.GetMappedTaskInstanceDependencies(context.Background(), dagId, dagRunId, taskId, mapIndex).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskInstanceAPIService GetMappedTaskInstanceTries", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dagId string
		var dagRunId string
		var taskId string
		var mapIndex int32

		resp, httpRes, err := apiClient.TaskInstanceAPI.GetMappedTaskInstanceTries(context.Background(), dagId, dagRunId, taskId, mapIndex).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskInstanceAPIService GetMappedTaskInstanceTryDetails", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dagId string
		var dagRunId string
		var taskId string
		var mapIndex int32
		var taskTryNumber int32

		resp, httpRes, err := apiClient.TaskInstanceAPI.GetMappedTaskInstanceTryDetails(context.Background(), dagId, dagRunId, taskId, mapIndex, taskTryNumber).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskInstanceAPIService GetMappedTaskInstances", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dagId string
		var dagRunId string
		var taskId string

		resp, httpRes, err := apiClient.TaskInstanceAPI.GetMappedTaskInstances(context.Background(), dagId, dagRunId, taskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskInstanceAPIService GetTaskInstance", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dagId string
		var dagRunId string
		var taskId string

		resp, httpRes, err := apiClient.TaskInstanceAPI.GetTaskInstance(context.Background(), dagId, dagRunId, taskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskInstanceAPIService GetTaskInstanceDependencies", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dagId string
		var dagRunId string
		var taskId string

		resp, httpRes, err := apiClient.TaskInstanceAPI.GetTaskInstanceDependencies(context.Background(), dagId, dagRunId, taskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskInstanceAPIService GetTaskInstanceTries", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dagId string
		var dagRunId string
		var taskId string

		resp, httpRes, err := apiClient.TaskInstanceAPI.GetTaskInstanceTries(context.Background(), dagId, dagRunId, taskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskInstanceAPIService GetTaskInstanceTryDetails", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dagId string
		var dagRunId string
		var taskId string
		var taskTryNumber int32

		resp, httpRes, err := apiClient.TaskInstanceAPI.GetTaskInstanceTryDetails(context.Background(), dagId, dagRunId, taskId, taskTryNumber).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskInstanceAPIService GetTaskInstances", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dagId string
		var dagRunId string

		resp, httpRes, err := apiClient.TaskInstanceAPI.GetTaskInstances(context.Background(), dagId, dagRunId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskInstanceAPIService GetTaskInstancesBatch", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.TaskInstanceAPI.GetTaskInstancesBatch(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskInstanceAPIService PatchMappedTaskInstance", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dagId string
		var dagRunId string
		var taskId string
		var mapIndex int32

		resp, httpRes, err := apiClient.TaskInstanceAPI.PatchMappedTaskInstance(context.Background(), dagId, dagRunId, taskId, mapIndex).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskInstanceAPIService PatchTaskInstance", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dagId string
		var dagRunId string
		var taskId string

		resp, httpRes, err := apiClient.TaskInstanceAPI.PatchTaskInstance(context.Background(), dagId, dagRunId, taskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskInstanceAPIService SetMappedTaskInstanceNote", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dagId string
		var dagRunId string
		var taskId string
		var mapIndex int32

		resp, httpRes, err := apiClient.TaskInstanceAPI.SetMappedTaskInstanceNote(context.Background(), dagId, dagRunId, taskId, mapIndex).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaskInstanceAPIService SetTaskInstanceNote", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dagId string
		var dagRunId string
		var taskId string

		resp, httpRes, err := apiClient.TaskInstanceAPI.SetTaskInstanceNote(context.Background(), dagId, dagRunId, taskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
