/*
Airflow API (Stable)

Testing DAGRunAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package airflow

import (
	openapiclient "github.com/drfaust92/airflow-client-go/airflow"
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_airflow_DAGRunAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DAGRunAPIService ClearDagRun", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dagId string
		var dagRunId string

		resp, httpRes, err := apiClient.DAGRunAPI.ClearDagRun(context.Background(), dagId, dagRunId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DAGRunAPIService DeleteDagRun", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dagId string
		var dagRunId string

		httpRes, err := apiClient.DAGRunAPI.DeleteDagRun(context.Background(), dagId, dagRunId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DAGRunAPIService GetDagRun", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dagId string
		var dagRunId string

		resp, httpRes, err := apiClient.DAGRunAPI.GetDagRun(context.Background(), dagId, dagRunId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DAGRunAPIService GetDagRuns", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dagId string

		resp, httpRes, err := apiClient.DAGRunAPI.GetDagRuns(context.Background(), dagId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DAGRunAPIService GetDagRunsBatch", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.DAGRunAPI.GetDagRunsBatch(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DAGRunAPIService GetUpstreamDatasetEvents", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dagId string
		var dagRunId string

		resp, httpRes, err := apiClient.DAGRunAPI.GetUpstreamDatasetEvents(context.Background(), dagId, dagRunId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DAGRunAPIService PostDagRun", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dagId string

		resp, httpRes, err := apiClient.DAGRunAPI.PostDagRun(context.Background(), dagId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DAGRunAPIService SetDagRunNote", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dagId string
		var dagRunId string

		resp, httpRes, err := apiClient.DAGRunAPI.SetDagRunNote(context.Background(), dagId, dagRunId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DAGRunAPIService UpdateDagRunState", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var dagId string
		var dagRunId string

		resp, httpRes, err := apiClient.DAGRunAPI.UpdateDagRunState(context.Background(), dagId, dagRunId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
