/*
Airflow API (Stable)

Testing PluginAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package airflow

import (
	openapiclient "github.com/drfaust92/airflow-client-go/airflow"
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_airflow_PluginAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PluginAPIService GetPlugins", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.PluginAPI.GetPlugins(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
