/*
Airflow API (Stable)

Testing RoleAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package airflow

import (
	openapiclient "./airflow"
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_airflow_RoleAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RoleAPIService DeleteRole", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var roleName string

		httpRes, err := apiClient.RoleAPI.DeleteRole(context.Background(), roleName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RoleAPIService GetRole", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var roleName string

		resp, httpRes, err := apiClient.RoleAPI.GetRole(context.Background(), roleName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RoleAPIService GetRoles", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.RoleAPI.GetRoles(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RoleAPIService PatchRole", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var roleName string

		resp, httpRes, err := apiClient.RoleAPI.PatchRole(context.Background(), roleName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RoleAPIService PostRole", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.RoleAPI.PostRole(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
