/*
Flask App Builder User & Role API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: dev@airflow.apache.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fab

import (
	"encoding/json"
)

// checks if the UserCollectionItemRolesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserCollectionItemRolesInner{}

// UserCollectionItemRolesInner struct for UserCollectionItemRolesInner
type UserCollectionItemRolesInner struct {
	Name *string `json:"name,omitempty"`
}

// NewUserCollectionItemRolesInner instantiates a new UserCollectionItemRolesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserCollectionItemRolesInner() *UserCollectionItemRolesInner {
	this := UserCollectionItemRolesInner{}
	return &this
}

// NewUserCollectionItemRolesInnerWithDefaults instantiates a new UserCollectionItemRolesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserCollectionItemRolesInnerWithDefaults() *UserCollectionItemRolesInner {
	this := UserCollectionItemRolesInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UserCollectionItemRolesInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCollectionItemRolesInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UserCollectionItemRolesInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UserCollectionItemRolesInner) SetName(v string) {
	o.Name = &v
}

func (o UserCollectionItemRolesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserCollectionItemRolesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableUserCollectionItemRolesInner struct {
	value *UserCollectionItemRolesInner
	isSet bool
}

func (v NullableUserCollectionItemRolesInner) Get() *UserCollectionItemRolesInner {
	return v.value
}

func (v *NullableUserCollectionItemRolesInner) Set(val *UserCollectionItemRolesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableUserCollectionItemRolesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableUserCollectionItemRolesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserCollectionItemRolesInner(val *UserCollectionItemRolesInner) *NullableUserCollectionItemRolesInner {
	return &NullableUserCollectionItemRolesInner{value: val, isSet: true}
}

func (v NullableUserCollectionItemRolesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserCollectionItemRolesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


