/*
Flask App Builder User & Role API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: dev@airflow.apache.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fab

import (
	"encoding/json"
)

// checks if the ActionCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActionCollection{}

// ActionCollection A collection of actions.  *New in version 2.8.0* 
type ActionCollection struct {
	// Count of total objects in the current result set before pagination parameters (limit, offset) are applied. 
	TotalEntries *int32 `json:"total_entries,omitempty"`
	Actions []Action `json:"actions,omitempty"`
}

// NewActionCollection instantiates a new ActionCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActionCollection() *ActionCollection {
	this := ActionCollection{}
	return &this
}

// NewActionCollectionWithDefaults instantiates a new ActionCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActionCollectionWithDefaults() *ActionCollection {
	this := ActionCollection{}
	return &this
}

// GetTotalEntries returns the TotalEntries field value if set, zero value otherwise.
func (o *ActionCollection) GetTotalEntries() int32 {
	if o == nil || IsNil(o.TotalEntries) {
		var ret int32
		return ret
	}
	return *o.TotalEntries
}

// GetTotalEntriesOk returns a tuple with the TotalEntries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActionCollection) GetTotalEntriesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalEntries) {
		return nil, false
	}
	return o.TotalEntries, true
}

// HasTotalEntries returns a boolean if a field has been set.
func (o *ActionCollection) HasTotalEntries() bool {
	if o != nil && !IsNil(o.TotalEntries) {
		return true
	}

	return false
}

// SetTotalEntries gets a reference to the given int32 and assigns it to the TotalEntries field.
func (o *ActionCollection) SetTotalEntries(v int32) {
	o.TotalEntries = &v
}

// GetActions returns the Actions field value if set, zero value otherwise.
func (o *ActionCollection) GetActions() []Action {
	if o == nil || IsNil(o.Actions) {
		var ret []Action
		return ret
	}
	return o.Actions
}

// GetActionsOk returns a tuple with the Actions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActionCollection) GetActionsOk() ([]Action, bool) {
	if o == nil || IsNil(o.Actions) {
		return nil, false
	}
	return o.Actions, true
}

// HasActions returns a boolean if a field has been set.
func (o *ActionCollection) HasActions() bool {
	if o != nil && !IsNil(o.Actions) {
		return true
	}

	return false
}

// SetActions gets a reference to the given []Action and assigns it to the Actions field.
func (o *ActionCollection) SetActions(v []Action) {
	o.Actions = v
}

func (o ActionCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActionCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TotalEntries) {
		toSerialize["total_entries"] = o.TotalEntries
	}
	if !IsNil(o.Actions) {
		toSerialize["actions"] = o.Actions
	}
	return toSerialize, nil
}

type NullableActionCollection struct {
	value *ActionCollection
	isSet bool
}

func (v NullableActionCollection) Get() *ActionCollection {
	return v.value
}

func (v *NullableActionCollection) Set(val *ActionCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableActionCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableActionCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActionCollection(val *ActionCollection) *NullableActionCollection {
	return &NullableActionCollection{value: val, isSet: true}
}

func (v NullableActionCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActionCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


