/*
Flask App Builder User & Role API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: dev@airflow.apache.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fab

import (
	"encoding/json"
)

// checks if the ActionResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActionResource{}

// ActionResource The Action-Resource item.  *New in version 2.8.0* 
type ActionResource struct {
	Action *Action `json:"action,omitempty"`
	Resource *Resource `json:"resource,omitempty"`
}

// NewActionResource instantiates a new ActionResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActionResource() *ActionResource {
	this := ActionResource{}
	return &this
}

// NewActionResourceWithDefaults instantiates a new ActionResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActionResourceWithDefaults() *ActionResource {
	this := ActionResource{}
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *ActionResource) GetAction() Action {
	if o == nil || IsNil(o.Action) {
		var ret Action
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActionResource) GetActionOk() (*Action, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *ActionResource) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given Action and assigns it to the Action field.
func (o *ActionResource) SetAction(v Action) {
	o.Action = &v
}

// GetResource returns the Resource field value if set, zero value otherwise.
func (o *ActionResource) GetResource() Resource {
	if o == nil || IsNil(o.Resource) {
		var ret Resource
		return ret
	}
	return *o.Resource
}

// GetResourceOk returns a tuple with the Resource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActionResource) GetResourceOk() (*Resource, bool) {
	if o == nil || IsNil(o.Resource) {
		return nil, false
	}
	return o.Resource, true
}

// HasResource returns a boolean if a field has been set.
func (o *ActionResource) HasResource() bool {
	if o != nil && !IsNil(o.Resource) {
		return true
	}

	return false
}

// SetResource gets a reference to the given Resource and assigns it to the Resource field.
func (o *ActionResource) SetResource(v Resource) {
	o.Resource = &v
}

func (o ActionResource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActionResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	if !IsNil(o.Resource) {
		toSerialize["resource"] = o.Resource
	}
	return toSerialize, nil
}

type NullableActionResource struct {
	value *ActionResource
	isSet bool
}

func (v NullableActionResource) Get() *ActionResource {
	return v.value
}

func (v *NullableActionResource) Set(val *ActionResource) {
	v.value = val
	v.isSet = true
}

func (v NullableActionResource) IsSet() bool {
	return v.isSet
}

func (v *NullableActionResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActionResource(val *ActionResource) *NullableActionResource {
	return &NullableActionResource{value: val, isSet: true}
}

func (v NullableActionResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActionResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


