/*
Flask App Builder User & Role API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: dev@airflow.apache.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fab

import (
	"encoding/json"
)

// checks if the RoleCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoleCollection{}

// RoleCollection A collection of roles.  *New in version 2.8.0* 
type RoleCollection struct {
	// Count of total objects in the current result set before pagination parameters (limit, offset) are applied. 
	TotalEntries *int32 `json:"total_entries,omitempty"`
	Roles []Role `json:"roles,omitempty"`
}

// NewRoleCollection instantiates a new RoleCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoleCollection() *RoleCollection {
	this := RoleCollection{}
	return &this
}

// NewRoleCollectionWithDefaults instantiates a new RoleCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoleCollectionWithDefaults() *RoleCollection {
	this := RoleCollection{}
	return &this
}

// GetTotalEntries returns the TotalEntries field value if set, zero value otherwise.
func (o *RoleCollection) GetTotalEntries() int32 {
	if o == nil || IsNil(o.TotalEntries) {
		var ret int32
		return ret
	}
	return *o.TotalEntries
}

// GetTotalEntriesOk returns a tuple with the TotalEntries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleCollection) GetTotalEntriesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalEntries) {
		return nil, false
	}
	return o.TotalEntries, true
}

// HasTotalEntries returns a boolean if a field has been set.
func (o *RoleCollection) HasTotalEntries() bool {
	if o != nil && !IsNil(o.TotalEntries) {
		return true
	}

	return false
}

// SetTotalEntries gets a reference to the given int32 and assigns it to the TotalEntries field.
func (o *RoleCollection) SetTotalEntries(v int32) {
	o.TotalEntries = &v
}

// GetRoles returns the Roles field value if set, zero value otherwise.
func (o *RoleCollection) GetRoles() []Role {
	if o == nil || IsNil(o.Roles) {
		var ret []Role
		return ret
	}
	return o.Roles
}

// GetRolesOk returns a tuple with the Roles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleCollection) GetRolesOk() ([]Role, bool) {
	if o == nil || IsNil(o.Roles) {
		return nil, false
	}
	return o.Roles, true
}

// HasRoles returns a boolean if a field has been set.
func (o *RoleCollection) HasRoles() bool {
	if o != nil && !IsNil(o.Roles) {
		return true
	}

	return false
}

// SetRoles gets a reference to the given []Role and assigns it to the Roles field.
func (o *RoleCollection) SetRoles(v []Role) {
	o.Roles = v
}

func (o RoleCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoleCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TotalEntries) {
		toSerialize["total_entries"] = o.TotalEntries
	}
	if !IsNil(o.Roles) {
		toSerialize["roles"] = o.Roles
	}
	return toSerialize, nil
}

type NullableRoleCollection struct {
	value *RoleCollection
	isSet bool
}

func (v NullableRoleCollection) Get() *RoleCollection {
	return v.value
}

func (v *NullableRoleCollection) Set(val *RoleCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableRoleCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableRoleCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoleCollection(val *RoleCollection) *NullableRoleCollection {
	return &NullableRoleCollection{value: val, isSet: true}
}

func (v NullableRoleCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoleCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


