/*
Flask App Builder User & Role API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: dev@airflow.apache.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fab

import (
	"encoding/json"
)

// checks if the CollectionInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CollectionInfo{}

// CollectionInfo Metadata about collection.
type CollectionInfo struct {
	// Count of total objects in the current result set before pagination parameters (limit, offset) are applied. 
	TotalEntries *int32 `json:"total_entries,omitempty"`
}

// NewCollectionInfo instantiates a new CollectionInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCollectionInfo() *CollectionInfo {
	this := CollectionInfo{}
	return &this
}

// NewCollectionInfoWithDefaults instantiates a new CollectionInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCollectionInfoWithDefaults() *CollectionInfo {
	this := CollectionInfo{}
	return &this
}

// GetTotalEntries returns the TotalEntries field value if set, zero value otherwise.
func (o *CollectionInfo) GetTotalEntries() int32 {
	if o == nil || IsNil(o.TotalEntries) {
		var ret int32
		return ret
	}
	return *o.TotalEntries
}

// GetTotalEntriesOk returns a tuple with the TotalEntries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionInfo) GetTotalEntriesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalEntries) {
		return nil, false
	}
	return o.TotalEntries, true
}

// HasTotalEntries returns a boolean if a field has been set.
func (o *CollectionInfo) HasTotalEntries() bool {
	if o != nil && !IsNil(o.TotalEntries) {
		return true
	}

	return false
}

// SetTotalEntries gets a reference to the given int32 and assigns it to the TotalEntries field.
func (o *CollectionInfo) SetTotalEntries(v int32) {
	o.TotalEntries = &v
}

func (o CollectionInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CollectionInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TotalEntries) {
		toSerialize["total_entries"] = o.TotalEntries
	}
	return toSerialize, nil
}

type NullableCollectionInfo struct {
	value *CollectionInfo
	isSet bool
}

func (v NullableCollectionInfo) Get() *CollectionInfo {
	return v.value
}

func (v *NullableCollectionInfo) Set(val *CollectionInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableCollectionInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableCollectionInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCollectionInfo(val *CollectionInfo) *NullableCollectionInfo {
	return &NullableCollectionInfo{value: val, isSet: true}
}

func (v NullableCollectionInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCollectionInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


