/*
Flask App Builder User & Role API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: dev@airflow.apache.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fab

import (
	"encoding/json"
)

// checks if the UserCollectionItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserCollectionItem{}

// UserCollectionItem A user object.  *New in version 2.8.0* 
type UserCollectionItem struct {
	// Whether the user is active
	Active NullableBool `json:"active,omitempty"`
	// The date user was changed
	ChangedOn NullableString `json:"changed_on,omitempty"`
	// The date user was created
	CreatedOn NullableString `json:"created_on,omitempty"`
	// The user's email. 
	Email *string `json:"email,omitempty"`
	// The number of times the login failed
	FailedLoginCount NullableInt32 `json:"failed_login_count,omitempty"`
	// The user's first name. 
	FirstName *string `json:"first_name,omitempty"`
	// The last user login
	LastLogin NullableString `json:"last_login,omitempty"`
	// The user's last name. 
	LastName *string `json:"last_name,omitempty"`
	// The login count
	LoginCount NullableInt32 `json:"login_count,omitempty"`
	// User roles. 
	Roles []UserCollectionItemRolesInner `json:"roles,omitempty"`
	// The username. 
	Username *string `json:"username,omitempty"`
}

// NewUserCollectionItem instantiates a new UserCollectionItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserCollectionItem() *UserCollectionItem {
	this := UserCollectionItem{}
	return &this
}

// NewUserCollectionItemWithDefaults instantiates a new UserCollectionItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserCollectionItemWithDefaults() *UserCollectionItem {
	this := UserCollectionItem{}
	return &this
}

// GetActive returns the Active field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserCollectionItem) GetActive() bool {
	if o == nil || IsNil(o.Active.Get()) {
		var ret bool
		return ret
	}
	return *o.Active.Get()
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserCollectionItem) GetActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Active.Get(), o.Active.IsSet()
}

// HasActive returns a boolean if a field has been set.
func (o *UserCollectionItem) HasActive() bool {
	if o != nil && o.Active.IsSet() {
		return true
	}

	return false
}

// SetActive gets a reference to the given NullableBool and assigns it to the Active field.
func (o *UserCollectionItem) SetActive(v bool) {
	o.Active.Set(&v)
}
// SetActiveNil sets the value for Active to be an explicit nil
func (o *UserCollectionItem) SetActiveNil() {
	o.Active.Set(nil)
}

// UnsetActive ensures that no value is present for Active, not even an explicit nil
func (o *UserCollectionItem) UnsetActive() {
	o.Active.Unset()
}

// GetChangedOn returns the ChangedOn field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserCollectionItem) GetChangedOn() string {
	if o == nil || IsNil(o.ChangedOn.Get()) {
		var ret string
		return ret
	}
	return *o.ChangedOn.Get()
}

// GetChangedOnOk returns a tuple with the ChangedOn field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserCollectionItem) GetChangedOnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ChangedOn.Get(), o.ChangedOn.IsSet()
}

// HasChangedOn returns a boolean if a field has been set.
func (o *UserCollectionItem) HasChangedOn() bool {
	if o != nil && o.ChangedOn.IsSet() {
		return true
	}

	return false
}

// SetChangedOn gets a reference to the given NullableString and assigns it to the ChangedOn field.
func (o *UserCollectionItem) SetChangedOn(v string) {
	o.ChangedOn.Set(&v)
}
// SetChangedOnNil sets the value for ChangedOn to be an explicit nil
func (o *UserCollectionItem) SetChangedOnNil() {
	o.ChangedOn.Set(nil)
}

// UnsetChangedOn ensures that no value is present for ChangedOn, not even an explicit nil
func (o *UserCollectionItem) UnsetChangedOn() {
	o.ChangedOn.Unset()
}

// GetCreatedOn returns the CreatedOn field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserCollectionItem) GetCreatedOn() string {
	if o == nil || IsNil(o.CreatedOn.Get()) {
		var ret string
		return ret
	}
	return *o.CreatedOn.Get()
}

// GetCreatedOnOk returns a tuple with the CreatedOn field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserCollectionItem) GetCreatedOnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedOn.Get(), o.CreatedOn.IsSet()
}

// HasCreatedOn returns a boolean if a field has been set.
func (o *UserCollectionItem) HasCreatedOn() bool {
	if o != nil && o.CreatedOn.IsSet() {
		return true
	}

	return false
}

// SetCreatedOn gets a reference to the given NullableString and assigns it to the CreatedOn field.
func (o *UserCollectionItem) SetCreatedOn(v string) {
	o.CreatedOn.Set(&v)
}
// SetCreatedOnNil sets the value for CreatedOn to be an explicit nil
func (o *UserCollectionItem) SetCreatedOnNil() {
	o.CreatedOn.Set(nil)
}

// UnsetCreatedOn ensures that no value is present for CreatedOn, not even an explicit nil
func (o *UserCollectionItem) UnsetCreatedOn() {
	o.CreatedOn.Unset()
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *UserCollectionItem) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCollectionItem) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *UserCollectionItem) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *UserCollectionItem) SetEmail(v string) {
	o.Email = &v
}

// GetFailedLoginCount returns the FailedLoginCount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserCollectionItem) GetFailedLoginCount() int32 {
	if o == nil || IsNil(o.FailedLoginCount.Get()) {
		var ret int32
		return ret
	}
	return *o.FailedLoginCount.Get()
}

// GetFailedLoginCountOk returns a tuple with the FailedLoginCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserCollectionItem) GetFailedLoginCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.FailedLoginCount.Get(), o.FailedLoginCount.IsSet()
}

// HasFailedLoginCount returns a boolean if a field has been set.
func (o *UserCollectionItem) HasFailedLoginCount() bool {
	if o != nil && o.FailedLoginCount.IsSet() {
		return true
	}

	return false
}

// SetFailedLoginCount gets a reference to the given NullableInt32 and assigns it to the FailedLoginCount field.
func (o *UserCollectionItem) SetFailedLoginCount(v int32) {
	o.FailedLoginCount.Set(&v)
}
// SetFailedLoginCountNil sets the value for FailedLoginCount to be an explicit nil
func (o *UserCollectionItem) SetFailedLoginCountNil() {
	o.FailedLoginCount.Set(nil)
}

// UnsetFailedLoginCount ensures that no value is present for FailedLoginCount, not even an explicit nil
func (o *UserCollectionItem) UnsetFailedLoginCount() {
	o.FailedLoginCount.Unset()
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *UserCollectionItem) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCollectionItem) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *UserCollectionItem) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *UserCollectionItem) SetFirstName(v string) {
	o.FirstName = &v
}

// GetLastLogin returns the LastLogin field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserCollectionItem) GetLastLogin() string {
	if o == nil || IsNil(o.LastLogin.Get()) {
		var ret string
		return ret
	}
	return *o.LastLogin.Get()
}

// GetLastLoginOk returns a tuple with the LastLogin field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserCollectionItem) GetLastLoginOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastLogin.Get(), o.LastLogin.IsSet()
}

// HasLastLogin returns a boolean if a field has been set.
func (o *UserCollectionItem) HasLastLogin() bool {
	if o != nil && o.LastLogin.IsSet() {
		return true
	}

	return false
}

// SetLastLogin gets a reference to the given NullableString and assigns it to the LastLogin field.
func (o *UserCollectionItem) SetLastLogin(v string) {
	o.LastLogin.Set(&v)
}
// SetLastLoginNil sets the value for LastLogin to be an explicit nil
func (o *UserCollectionItem) SetLastLoginNil() {
	o.LastLogin.Set(nil)
}

// UnsetLastLogin ensures that no value is present for LastLogin, not even an explicit nil
func (o *UserCollectionItem) UnsetLastLogin() {
	o.LastLogin.Unset()
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *UserCollectionItem) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCollectionItem) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *UserCollectionItem) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *UserCollectionItem) SetLastName(v string) {
	o.LastName = &v
}

// GetLoginCount returns the LoginCount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserCollectionItem) GetLoginCount() int32 {
	if o == nil || IsNil(o.LoginCount.Get()) {
		var ret int32
		return ret
	}
	return *o.LoginCount.Get()
}

// GetLoginCountOk returns a tuple with the LoginCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserCollectionItem) GetLoginCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LoginCount.Get(), o.LoginCount.IsSet()
}

// HasLoginCount returns a boolean if a field has been set.
func (o *UserCollectionItem) HasLoginCount() bool {
	if o != nil && o.LoginCount.IsSet() {
		return true
	}

	return false
}

// SetLoginCount gets a reference to the given NullableInt32 and assigns it to the LoginCount field.
func (o *UserCollectionItem) SetLoginCount(v int32) {
	o.LoginCount.Set(&v)
}
// SetLoginCountNil sets the value for LoginCount to be an explicit nil
func (o *UserCollectionItem) SetLoginCountNil() {
	o.LoginCount.Set(nil)
}

// UnsetLoginCount ensures that no value is present for LoginCount, not even an explicit nil
func (o *UserCollectionItem) UnsetLoginCount() {
	o.LoginCount.Unset()
}

// GetRoles returns the Roles field value if set, zero value otherwise.
func (o *UserCollectionItem) GetRoles() []UserCollectionItemRolesInner {
	if o == nil || IsNil(o.Roles) {
		var ret []UserCollectionItemRolesInner
		return ret
	}
	return o.Roles
}

// GetRolesOk returns a tuple with the Roles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCollectionItem) GetRolesOk() ([]UserCollectionItemRolesInner, bool) {
	if o == nil || IsNil(o.Roles) {
		return nil, false
	}
	return o.Roles, true
}

// HasRoles returns a boolean if a field has been set.
func (o *UserCollectionItem) HasRoles() bool {
	if o != nil && !IsNil(o.Roles) {
		return true
	}

	return false
}

// SetRoles gets a reference to the given []UserCollectionItemRolesInner and assigns it to the Roles field.
func (o *UserCollectionItem) SetRoles(v []UserCollectionItemRolesInner) {
	o.Roles = v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *UserCollectionItem) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCollectionItem) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *UserCollectionItem) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *UserCollectionItem) SetUsername(v string) {
	o.Username = &v
}

func (o UserCollectionItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserCollectionItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Active.IsSet() {
		toSerialize["active"] = o.Active.Get()
	}
	if o.ChangedOn.IsSet() {
		toSerialize["changed_on"] = o.ChangedOn.Get()
	}
	if o.CreatedOn.IsSet() {
		toSerialize["created_on"] = o.CreatedOn.Get()
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if o.FailedLoginCount.IsSet() {
		toSerialize["failed_login_count"] = o.FailedLoginCount.Get()
	}
	if !IsNil(o.FirstName) {
		toSerialize["first_name"] = o.FirstName
	}
	if o.LastLogin.IsSet() {
		toSerialize["last_login"] = o.LastLogin.Get()
	}
	if !IsNil(o.LastName) {
		toSerialize["last_name"] = o.LastName
	}
	if o.LoginCount.IsSet() {
		toSerialize["login_count"] = o.LoginCount.Get()
	}
	if !IsNil(o.Roles) {
		toSerialize["roles"] = o.Roles
	}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	return toSerialize, nil
}

type NullableUserCollectionItem struct {
	value *UserCollectionItem
	isSet bool
}

func (v NullableUserCollectionItem) Get() *UserCollectionItem {
	return v.value
}

func (v *NullableUserCollectionItem) Set(val *UserCollectionItem) {
	v.value = val
	v.isSet = true
}

func (v NullableUserCollectionItem) IsSet() bool {
	return v.isSet
}

func (v *NullableUserCollectionItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserCollectionItem(val *UserCollectionItem) *NullableUserCollectionItem {
	return &NullableUserCollectionItem{value: val, isSet: true}
}

func (v NullableUserCollectionItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserCollectionItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


