/*
Flask App Builder User & Role API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: dev@airflow.apache.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fab

import (
	"encoding/json"
)

// checks if the UserCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserCollection{}

// UserCollection Collection of users.  *New in version 2.8.0* 
type UserCollection struct {
	// Count of total objects in the current result set before pagination parameters (limit, offset) are applied. 
	TotalEntries *int32 `json:"total_entries,omitempty"`
	Users []UserCollectionItem `json:"users,omitempty"`
}

// NewUserCollection instantiates a new UserCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserCollection() *UserCollection {
	this := UserCollection{}
	return &this
}

// NewUserCollectionWithDefaults instantiates a new UserCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserCollectionWithDefaults() *UserCollection {
	this := UserCollection{}
	return &this
}

// GetTotalEntries returns the TotalEntries field value if set, zero value otherwise.
func (o *UserCollection) GetTotalEntries() int32 {
	if o == nil || IsNil(o.TotalEntries) {
		var ret int32
		return ret
	}
	return *o.TotalEntries
}

// GetTotalEntriesOk returns a tuple with the TotalEntries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCollection) GetTotalEntriesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalEntries) {
		return nil, false
	}
	return o.TotalEntries, true
}

// HasTotalEntries returns a boolean if a field has been set.
func (o *UserCollection) HasTotalEntries() bool {
	if o != nil && !IsNil(o.TotalEntries) {
		return true
	}

	return false
}

// SetTotalEntries gets a reference to the given int32 and assigns it to the TotalEntries field.
func (o *UserCollection) SetTotalEntries(v int32) {
	o.TotalEntries = &v
}

// GetUsers returns the Users field value if set, zero value otherwise.
func (o *UserCollection) GetUsers() []UserCollectionItem {
	if o == nil || IsNil(o.Users) {
		var ret []UserCollectionItem
		return ret
	}
	return o.Users
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCollection) GetUsersOk() ([]UserCollectionItem, bool) {
	if o == nil || IsNil(o.Users) {
		return nil, false
	}
	return o.Users, true
}

// HasUsers returns a boolean if a field has been set.
func (o *UserCollection) HasUsers() bool {
	if o != nil && !IsNil(o.Users) {
		return true
	}

	return false
}

// SetUsers gets a reference to the given []UserCollectionItem and assigns it to the Users field.
func (o *UserCollection) SetUsers(v []UserCollectionItem) {
	o.Users = v
}

func (o UserCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TotalEntries) {
		toSerialize["total_entries"] = o.TotalEntries
	}
	if !IsNil(o.Users) {
		toSerialize["users"] = o.Users
	}
	return toSerialize, nil
}

type NullableUserCollection struct {
	value *UserCollection
	isSet bool
}

func (v NullableUserCollection) Get() *UserCollection {
	return v.value
}

func (v *NullableUserCollection) Set(val *UserCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableUserCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableUserCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserCollection(val *UserCollection) *NullableUserCollection {
	return &NullableUserCollection{value: val, isSet: true}
}

func (v NullableUserCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


